### ISSUE TITLE
PubControlClient doesn't retry http requests

### ISSUE THREAD

**Issue by noamkush** [fanout/pypubcontrol#2]
When there's any connection issue, PubControlClient immediately throws an error. There's no attempt to retry immediately or using backoff. It would be nice to have a way to configure this externally and a decent default.

**Comment by jkarneges** [comment]
I just pushed 3.0.0 with a fix. The library will automatically try one time after failure, to get around potential session timeouts. This is similar to what some database client libraries will do.

At the moment you'll need to install this version explicitly, as it's a major version bump and the higher level libraries haven't been updated to allow this version yet. But it should work fine with them. Let me know if this solves your issue.

If more retries are needed we could consider increasing the number or making it configurable. However retrying the same message too many times could slow down processing of newer messages, and newer messages are often more important in realtime systems than late messages, so I started with a conservative number.

**Comment by jkarneges** [comment]
As discussed separately, this is considered resolved.
