### ISSUE TITLE
Poetry package manager gets the PyJWT dependency version wrong

### ISSUE THREAD

**Issue by foucdeg** [fanout/pypubcontrol#5]
I first filed this issue against the Poetry repo:

https://github.com/python-poetry/poetry/issues/5218

The first answer points out that the published `requirements.txt` file fo this package mentions PyJWT <2 as a dependency, while according to the `setup.py` file, for python3, PyJWT >=2 <3 is allowed.

The impact is that I can't install django-eventstream in parallel with any package that requires PyJWT >=2.

Is there any workaround or fix?

**Comment by dimbleby** [comment]
per comment in upstream issue, this project should use markers to specify different versions of dependencies for different python versions, if it needs to do that.

I suspect it _doesn't_ need to do that, though, pyjwt 2.0 and later has a [python_requires](https://github.com/jpadilla/pyjwt/blob/2.0.0/setup.cfg#L35) in its setup which will be respected by all recent versions of pip (and poetry).  So probably this project should simply requires `pyjwt >= 1` and let the tooling find a version that's compatible with the environment in which it is being installed.

**Comment by foucdeg** [comment]
Hi @jkarneges, just wondering if you've had time to give this a look?

**Comment by jkarneges** [comment]
Version 3.3.0 has been posted with a fix.

Thanks @dimbleby for the suggestions. I noticed `python setup.py install` under Python 2 didn't obey PyJWT's `python_requires` so I used markers to be on the safe side.

**Comment by foucdeg** [comment]
Thank you!
